### ISSUE TITLE
Incohérence dispositifs médicaux

### ISSUE THREAD

**Issue by DrFabach** [aneuraz/medic-annotation-guide#1]
Dans le guide de référence il est noté : 
- Ligne 121, de ne pas annoté la pompe à insuline dans les médicaments 
- Ligne 199 l'exemple annote insuline.

Y a t-il une erreur, ou je n'ai pas compris?

**Comment by aneuraz** [comment]
Il y avait effectivement une incohérence. C'est corrigé. On annote les dispositifs médicaux s'ils contiennent une mention de médicament comme la pompe à insuline. Merci @DrFabach
